### ISSUE TITLE
never logged in after pressing start.

### ISSUE THREAD

**Issue by DanielGurianov** [adamb70/CSGO-Market-Float-Finder#19]
Every time I press start, an error appears-not logged into steam, please restart program.
log file- 
[log.txt](https://github.com/adamb70/CSGO-Market-Float-Finder/files/1675266/log.txt)

**Comment by Trendle** [comment]
> 
> 
> Every time I press start, an error appears-not logged into steam, please restart program.
> log file-
> [log.txt](https://github.com/adamb70/CSGO-Market-Float-Finder/files/1675266/log.txt)

I, too, downloaded this program and it didn't work. One week later someone tried to log into my account. Steam Guard saved my ass, but I had to change my password. Did this happen to you as well?

**Comment by DanielGurianov** [comment]
am not sure, was a long time ago.
Maybe someone tried, but I didnt lose my account or something like that.

**Comment by adamb70** [comment]
@Trendle If you choose to enable "remember me" on login, this program will save your username and password in plaintext in the local folder on your machine as explained in the first step of the instructions. You should only do this on a private machine. The login details are otherwise only used to authenticate with Steam and are subsequently forgotten.

Closing this issue for now as nobody else has reported a similar issue with logging in, and in the time since it opened this program has become somewhat obsolete.

**Comment by Trendle** [comment]
Wasn't the account I used with your program, it was another account that I forgot I even created. I noticed after I posted my comment, that's why I removed it.

**Comment by ghost** [comment]
@adamb70 Wasn't the account I used with your program, it was another account that I forgot I even created. I noticed after I posted my comment, that's why I removed it.
