### ISSUE TITLE
[Question] is it possible to program the bot to buy some specific float values as well?

### ISSUE THREAD

**Issue by VVILD** [adamb70/CSGO-Market-Float-Finder#4]
if it is possible . please give me a short guide i ll try to extend the project and you can review it.

**Comment by adamb70** [comment]
It is probably possible, as long as the [recent escrow update](https://www.reddit.com/r/SteamBot/comments/3udhkd/everything_related_to_escrow/) didn't change anything required for purchasing.

I don't know any specific details about it though, and you'd probably have a hard time doing it in Python because the [SteamKit port](https://bitbucket.org/AzuiSleet/pysteamkit/overview) this program is using lacks a lot of functionality and has no documentation, and most of what I added to it revolves around the game coordinator. You'd probably have an easier time using [Node Steam](https://github.com/seishun/node-steam/) unless you fancy writing a lot of utility code.

I'd also be careful about Steam's terms of service, because if your bot was discovered for auto-purchasing, your account and all items could possibly get deleted.
