### ISSUE TITLE
Why does this program require CS/logging into Steam?

### ISSUE THREAD

**Issue by whatthebaek** [adamb70/CSGO-Market-Float-Finder#9]
Hey there! I was perusing your code but figured I'd just ask because I'm trying to learn Python and code something similar to this myself. Why is logging into Steam with an account that owns Counter-Strike required? You're using the same paintwear method to retrieve float values as this guy https://github.com/Tewki/CSGO-Item-Floats-From-Inspect-Links and his site (glws.org) also doesn't require a login. Just wondering if I'm overlooking something here. Thanks for putting this together btw, if I wind up either a) learning to code this myself or b) making some money (lol) I'll def donate some skins to ya! Might want to put your trade link in the program description.

**Comment by whatthebaek** [comment]
To clarify, I'm writing this because 1) of a few gaps in my understanding of how this program functions with Python (I'm VERY new haha) but personally it's acting as a great motivator for me to learn and 2) for security reasons. I don't save my password on the local file, and Steam Guard is enabled, but after reading stories like this: https://www.reddit.com/r/GlobalOffensiveTrade/comments/495u17/discussioni_was_hacked_please_help/ where accounts are hijacked even with Mobile Authentication. Well. It's a huge leap of faith on my part continuing to use the app (til I understand all of it ofc lol). Especially since Valve stated recently that they're officially not duping items and replacing inventories anymore.

I know it's a lot to ask but maybe if you could annotate your code on github or comment in your source or someth I'd feel more secure. Or if you could just do a quick process-diagram-style explanation of how things execute? Thanks for understanding I really appreciate it!

One last thing, I'm trying to make an executable version of this for Mac, any ideas how I might be able to do that?

**Comment by whatthebaek** [comment]
Also a few minor bugs, the ones I noticed were if you purchase an item while it's still searching, or if you hit retrieve twice, it'll freeze at processing the first item after hitting start and require a restart/relog.

**Comment by adamb70** [comment]
Hi :) The logging in with an account that owns CS:GO is required here due to the way Steam Game Coordinator messages work. They essentially tell Steam that we are running the game from our account, exactly as the Steam program would when you actually run the game, and that lets us request data that the game would request. 

The end goal of the program is to retrieve the skin data held in the EconPreviewData message that Steam responds with when we request it, but Steam will only respond to us if it thinks we are playing CS:GO. Firstly though, for Steam to think we are playing CS:GO we must first tell it that we are signed in as somebody, and it will only accept that we are playing CS:GO if that account actually owns the game.

So there are three steps to follow with Game Coordinator messages,
1) Send a message telling Steam that you have logged in.
2) Send a message telling Steam that you are running a game.
3) Send your Game Coordinator message to Steam and wait for the response data.

For a better understanding (and better documentation) I would recommend looking through the node.js packages that I used as guidance for how to communicate with Steam, [node-csgo](https://github.com/joshuaferrara/node-csgo#initializing) and [node-steam](https://github.com/seishun/node-steam#usage) (particularly the [Game Coordinator part of node-steam](https://github.com/seishun/node-steam/tree/de7391aa67a22bb1e9071665ad53ad770b51aa73/lib/handlers/game_coordinator)). I have tried to keep the operation as similar to these two packages as possible.

This is the same method Tewki uses, but I think (I may be mistaken) that his website does not require signing in because on the back end of his site he already has an account signed in and sending messages to Steam, which then just gives the result back to you. Likewise, I could probably ship this program with an account that it automatically signed into - but the login details would have to be the source code, or on a server, and I doubt it would be long before it got hijacked lol. Also I'm not sure how Steam would handle the same account being logged in multiple times.

I'm pretty new to Python myself, so I understand how complicated the SteamKit message system seems at first :P Yeah, it is very annoying storing login details in a plaintext file, I might be able to salt and hash them, but I don't know if that'd make it any more secure since the code is open-source - so anyone who gets a hold of the login details might still be able to decrypt them.

I'll try to add more comments into the code soon, but for now the basic overview of the code is as follows:
1. [Initialize the Steam Client](https://github.com/adamb70/CSGO-Market-Float-Finder/blob/master/FloatGetter.py#L155). This class operates similarly to the [node-steam](https://github.com/seishun/node-steam/tree/de7391aa67a22bb1e9071665ad53ad770b51aa73#steamclient) version.
2. [Initialize the Steam Game Coordinator](https://github.com/adamb70/CSGO-Market-Float-Finder/blob/master/FloatGetter.py#L156). This line also passes the CS:GO appID (730) to the Game Coordinator class, which is used in all messages to Steam from the Game Coordinator telling Steam which game you are requesting data from. This class is again similar to the [node-steam](https://github.com/seishun/node-steam/tree/de7391aa67a22bb1e9071665ad53ad770b51aa73/lib/handlers/game_coordinator) version. 
3. [Initialize the CSGO class](https://github.com/adamb70/CSGO-Market-Float-Finder/blob/master/FloatGetter.py#L157). This class is used to define all the functions we might need to send to to Steam 'from CS:GO'. It is similar to the [node-csgo](https://github.com/joshuaferrara/node-csgo#csgo) version ([Actual code](https://github.com/joshuaferrara/node-csgo/blob/master/index.js#L10)).
4. After all the initializing, we want to [log in](https://github.com/adamb70/CSGO-Market-Float-Finder/blob/master/FloatGetter.py#L159) to Steam. This takes your login details and sends them to Steam, then waits for a response saying that it was successful.
5. Once we are logged in to Steam we can tell it that we are [launching](https://github.com/adamb70/CSGO-Market-Float-Finder/blob/master/FloatGetter.py#L116) CS:GO. This tells Steam that we are playing CS:GO, then sends a 'hello' message to make Steam respond with a welcome message. If your account does not have CS:GO then you will not receive the welcome message. Again, this takes from [node-csgo](https://github.com/joshuaferrara/node-csgo/blob/master/index.js#L86). A nice way to check if Steam thinks you are playing CS:GO is to run the [set state](https://github.com/adamb70/CSGO-Market-Float-Finder/blob/master/FloatGetter.py#L170) function (`setState(1)`) any time after logging in. This will make you appear as online, and when Steam thinks you are playing CS:GO you will see your Steam account report that you are 'playing CS:GO'.
6. Request [float data](https://github.com/adamb70/CSGO-Market-Float-Finder/blob/master/FloatGetter.py#L129). This works exactly as Tewki shows in his code - it sends off a messages to Steam with the IDs for the skin, and waits for the reponse.
7. We can then [take the float data](https://github.com/adamb70/CSGO-Market-Float-Finder/blob/master/ui.py#L568), and [decode](https://github.com/adamb70/CSGO-Market-Float-Finder/blob/master/FloatGetter.py#L180) that value from UInt32 as Tewki does, to get a normal float.

I don't really know anything about creating a version for mac, I have very little knowledge of OSX and don't own a Mac to test. I used [PyInstaller](http://pythonhosted.org/PyInstaller/) to create the executable, and the [.spec file](https://github.com/adamb70/CSGO-Market-Float-Finder/blob/master/CSGO%20Market%20Float%20Finder.spec) is included in the source code, so rebuilding the executable is as simple as installing pyinstaller and doing `>pyinstaller "CSGO Market Float Finder.spec"` in Windows. For mac you would probably need to edit the spec file first to make the executable work for the OS ([This looks useful](http://pythonhosted.org/PyInstaller/#id40)). The GUI code in ui.py might cause you some problems too, and perhaps any path references. I used [PySide](http://pyside.readthedocs.org) (PyQt port) for the GUI, so you might need to look into how well that works with Mac. Good luck!

Thanks for reporting the bugs, I'll have a look into fixing them. Good idea with the trade link too, I'll add it to the description.

**Comment by whatthebaek** [comment]
Awesomely thorough reply Adam, I really appreciate it!! I'll get to reading into the links you provided asap, thank you again for making this! And I'll let you know if I get around to make a Mac client, Bootcamp works fine for now (though Parallels ironically does not)
